[tool.poetry]
name = "quick-cat"
version = "0.1.0"
description = "A script for concatenating files and preparing project summaries for LLMs"
authors = ["Federico A. Corazza <git@facorazza.com>"]
readme = "README.md"
license = "Apache-2.0"
packages = [{include = "quick_cat"}]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
flake8 = "^6.0.0"
mypy = "^1.3.0"

[tool.poetry.scripts]
quick-cat = "quick_cat.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38']

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true

[tool.flake8]
max-line-length = 100
extend-ignore = "E203"
