pub const DEFAULT_EXCLUDE_PATTERNS: &[&str] = &[
    // Compiled files and build artifacts
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.o",
    "*.so",
    "*.dll",
    "*.exe",
    "*.class",
    "*.jar",
    "*.war",
    "*.a",
    "*.lib",
    "*.dylib",
    "*.wasm",
    // Version control directories
    ".git/*",
    ".svn/*",
    ".hg/*",
    ".bzr/*",
    // System and hidden files
    ".DS_Store",
    "Thumbs.db",
    "*.tmp",
    "*.bak",
    "*.swp",
    "*.swo",
    "*~",
    "desktop.ini",
    ".Spotlight-V100",
    ".Trashes",
    // Development and IDE artifacts
    ".vscode/*",
    ".idea/*",
    "node_modules/*",
    "__pycache__/*",
    ".mypy_cache/*",
    ".pytest_cache/*",
    ".env",
    ".venv/*",
    "venv/*",
    "env/*",
    ".tox/*",
    ".coverage",
    "htmlcov/*",
    ".nyc_output/*",
    "coverage/*",
    ".sass-cache/*",
    ".next/*",
    ".nuxt/*",
    ".cache/*",
    // Build and distribution directories
    "build/*",
    "dist/*",
    "out/*",
    "*.egg-info/*",
    "target/*",
    "bin/*",
    "obj/*",
    "debug/*",
    "release/*",
    ".gradle/*",
    // Language-specific lock files
    "Cargo.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "composer.lock",
    "Pipfile.lock",
    "poetry.lock",
    "Gemfile.lock",
    "go.sum",
    // Media and binary files
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.gif",
    "*.bmp",
    "*.svg",
    "*.webp",
    "*.ico",
    "*.tiff",
    "*.tif",
    "*.psd",
    "*.ai",
    "*.sketch",
    "*.wav",
    "*.mp3",
    "*.mp4",
    "*.mov",
    "*.avi",
    "*.mkv",
    "*.flv",
    "*.wmv",
    "*.m4a",
    "*.aac",
    "*.ogg",
    "*.flac",
    // Compressed archives
    "*.zip",
    "*.tar",
    "*.gz",
    "*.rar",
    "*.7z",
    "*.bz2",
    "*.xz",
    "*.tgz",
    // Logs and temporary files
    "*.log",
    "logs/*",
    // Database files
    "*.sqlite",
    "*.sqlite3",
    "*.db",
    "*.mdb",
    "*.accdb",
    // Certificate and key files
    "*.pem",
    "*.key",
    "*.crt",
    "*.cer",
    "*.p12",
    "*.pfx",
    "*.jks",
    // Cloud and deployment
    ".terraform/*",
    "*.tfstate*",
    ".dockerignore",
];

pub const DEFAULT_INCLUDE_PATTERNS: &[&str] = &[
    // Programming languages
    "*.py",
    "*.pyw",
    "*.rs",
    "*.js",
    "*.mjs",
    "*.ts",
    "*.tsx",
    "*.jsx",
    "*.java",
    "*.kt",
    "*.scala",
    "*.clj",
    "*.c",
    "*.cpp",
    "*.cc",
    "*.cxx",
    "*.h",
    "*.hpp",
    "*.cs",
    "*.fs",
    "*.vb",
    "*.php",
    "*.rb",
    "*.go",
    "*.swift",
    "*.m",
    "*.mm",
    "*.dart",
    "*.lua",
    "*.pl",
    "*.r",
    "*.R",
    // Web technologies
    "*.html",
    "*.htm",
    "*.css",
    "*.scss",
    "*.sass",
    "*.less",
    "*.vue",
    "*.svelte",
    "*.astro",
    // Data and configuration
    "*.json",
    "*.jsonc",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.ini",
    "*.conf",
    "*.cfg",
    "*.properties",
    "*.env.example",
    "*.env.template",
    // Documentation
    "*.md",
    "*.markdown",
    "*.txt",
    "*.rst",
    "*.org",
    "*.tex",
    "*.adoc",
    "README*",
    "CHANGELOG*",
    "CONTRIBUTING*",
    // Build and project files
    "Makefile",
    "makefile",
    "Dockerfile*",
    "docker-compose*.yml",
    "*.gradle",
    "build.gradle*",
    "pom.xml",
    "requirements*.txt",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "Cargo.toml",
    "package.json",
    "composer.json",
    "Gemfile",
    "go.mod",
    "*.cmake",
    "CMakeLists.txt",
    // Shell and scripts
    "*.sh",
    "*.bash",
    "*.zsh",
    "*.fish",
    "*.ps1",
    "*.bat",
    "*.cmd",
    // Infrastructure as Code
    "*.tf",
    "*.tfvars",
    "*.hcl",
    "*.nomad",
    "*.consul",
    // CI/CD
    ".github/workflows/*.yml",
    ".github/workflows/*.yaml",
    ".gitlab-ci.yml",
    "azure-pipelines.yml",
    "Jenkinsfile",
    ".circleci/config.yml",
    ".travis.yml",
    // Database
    "*.sql",
    "*.pgsql",
    "*.mysql",
];
